import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildAeStyleMap, type AeStyleMapping } from "./ae-style-map.js";

/**
 * Writes `docs/AE-STYLE-COVERAGE.md` deterministically from `buildAeStyleMap()`. Run after any
 * change to `ae-style-map.ts`, `classification-rules.ts`, or `packages/caption-styles/styles/*.json`.
 *
 * Run with: `pnpm --filter @montaj/ae-cep generate:style-coverage`
 */

function renderMarkdown(mapping: AeStyleMapping[]): string {
  const counts = { supported: 0, approximate: 0, unsupported: 0 };
  for (const entry of mapping) counts[entry.support]++;

  const lines: string[] = [];
  lines.push("# After Effects styled-text-layer coverage (C05b, generated)");
  lines.push("");
  lines.push(
    "Generated by `pnpm --filter @montaj/ae-cep generate:style-coverage` from " +
      "`src/styles/ae-style-map.ts` (classification rules mirrored from C08b's " +
      "`plugins/resolve/aksharo_core_app/fusion/classification_rules.json`, see " +
      "`src/styles/classification-rules.ts` — same rule set C06b's Premiere MOGRT mapping " +
      "mirrors) against `packages/caption-styles/styles/*.json`. Do not edit by hand.",
  );
  lines.push("");
  lines.push(
    `**${counts.supported} supported, ${counts.approximate} approximate, ${counts.unsupported} unsupported** of ${mapping.length} styles.`,
  );
  lines.push("");
  lines.push(
    "Every style reaches picture regardless of this table: `src/apply/applyCaptions.ts` falls " +
      "back to the pre-rendered alpha overlay path (A20) whenever a style isn't text-layer-exact, " +
      'so *unsupported*/*approximate* here means "not a native, re-timeable styled text layer in ' +
      'the After Effects timeline", never "missing from the export."',
  );
  lines.push("");
  lines.push("| Style | Status | Reasons |");
  lines.push("|---|---|---|");
  for (const entry of mapping) {
    const status = entry.support.charAt(0).toUpperCase() + entry.support.slice(1);
    const reasons = entry.reasons.length > 0 ? entry.reasons.join(" ") : "—";
    lines.push(`| \`${entry.styleId}\` | ${status} | ${reasons} |`);
  }
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const mapping = buildAeStyleMap();
  const markdown = renderMarkdown(mapping);
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = join(here, "..", "..", "docs", "AE-STYLE-COVERAGE.md");
  writeFileSync(outPath, markdown);
  console.error(`wrote ${outPath} (${mapping.length} styles)`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}

export { renderMarkdown };
