import { describe, expect, it, vi } from "vitest";

import { RepurposeEpisodePackService, episodePackJobPrefix } from "./episode-pack.service.js";
import { AppException } from "../common/errors/error-codes.js";

import type { RepurposeRun } from "@prisma/client";

const WS = "01JCWS0000000000000000000A";
const PROJECT = "01JCPR0JECT000000000000000";
const RUN = "01JCRN0000000000000000000A";
const TRANSCRIPT = "01JCTRANSCR1PT000000000000";

const PACK = {
  chapters: [
    { startMs: 0, title: "Shuruaat" },
    { startMs: 60_000, title: "Salary ka jaal" },
  ],
  youtubeDescription: "Is video mein salary aur savings ki baat hai.",
  showNotes: "- Salary trap\n- Pehle khud ko pay karo",
  linkedinPost: "Salary badhna kaafi nahi hai. Aap kya sochte hain?",
  xThread: ["Salary se ameer kyun nahi bante?", "Kyunki kharcha bhi badhta hai."],
  newsletter: "Salary ka jaal\n\nIs hafte savings ki baat.",
  locale: "hi-Latn",
  source: "model",
};

interface Setup {
  readonly row?: { id: string; output: unknown; createdAt: Date } | null;
  readonly job?: { status: string } | null;
  readonly transcript?: { id: string; currentRevision: number; language: string } | null;
  readonly flag?: boolean;
  readonly config?: Record<string, unknown>;
  readonly requestFails?: boolean;
}

function harness(setup: Setup = {}) {
  const run = {
    id: RUN,
    workspaceId: WS,
    sourceProjectId: PROJECT,
    config: setup.config ?? {
      sourceLanguage: "auto",
      caption: { outputLanguage: "same", scriptMode: "roman", styleId: "punch-pop" },
    },
  } as unknown as RepurposeRun;
  const prisma = {
    repurposeRun: {
      findFirst: vi.fn(async (args: { where: { id: string; workspaceId: string } }) =>
        args.where.workspaceId === WS && args.where.id === RUN ? run : null,
      ),
    },
    transcript: {
      findFirst: vi.fn(async () =>
        setup.transcript === undefined
          ? { id: TRANSCRIPT, currentRevision: 3, language: "hi-Latn" }
          : setup.transcript,
      ),
    },
    job: { findFirst: vi.fn(async () => setup.job ?? null) },
  };
  const runs = { flagEnabled: vi.fn(async () => setup.flag ?? true) };
  const insights = {
    requestEpisodePack: vi.fn(async () => {
      if (setup.requestFails === true) throw new Error("queue down");
      return { jobId: "01JCJ0B0000000000000000000", deduplicated: false };
    }),
  };
  const outputs = { latestOfKind: vi.fn(async () => setup.row ?? null) };
  const service = new RepurposeEpisodePackService(
    prisma as never,
    runs as never,
    insights as never,
    outputs as never,
  );
  return { service, prisma, insights, outputs, run };
}

describe("RepurposeEpisodePackService — what the page reads", () => {
  it("is none before anything was asked", async () => {
    const h = harness();
    expect(await h.service.view(WS, RUN)).toMatchObject({
      runId: RUN,
      status: "none",
      pack: null,
      createdAt: null,
    });
  });

  it("is writing while its job is queued or running", async () => {
    for (const status of ["queued", "running"]) {
      const h = harness({ job: { status } });
      expect((await h.service.view(WS, RUN)).status, status).toBe("writing");
    }
  });

  it("is the pack once written, with the label shown on anything generated", async () => {
    const createdAt = new Date("2026-09-29T12:00:00Z");
    const h = harness({ row: { id: "o1", output: PACK, createdAt }, job: { status: "succeeded" } });
    const view = await h.service.view(WS, RUN);
    expect(view).toMatchObject({ status: "ready", pack: PACK, createdAt: createdAt.toISOString() });
    expect(view.disclosure).toBe("Generated by AI from your transcript");
    expect(h.outputs.latestOfKind).toHaveBeenCalledWith(PROJECT, "episode-pack");
  });

  it("is failed when its job ended without a pack", async () => {
    for (const status of ["failed", "cancelled", "succeeded"]) {
      const h = harness({ job: { status } });
      expect((await h.service.view(WS, RUN)).status, status).toBe("failed");
    }
  });

  it("looks only at this source video's pack jobs", async () => {
    const h = harness();
    await h.service.view(WS, RUN);
    expect(h.prisma.job.findFirst).toHaveBeenCalledWith(
      expect.objectContaining({
        where: expect.objectContaining({
          workspaceId: WS,
          projectId: PROJECT,
          type: "ai.llm",
          jobKey: { startsWith: `ai.llm:episode-pack:${PROJECT}:` },
        }),
      }),
    );
  });

  it("answers 404 for another workspace's run and while the feature is off", async () => {
    await expect(harness().service.view("01JCWS0000000000000000000B", RUN)).rejects.toBeInstanceOf(
      AppException,
    );
    await expect(harness({ flag: false }).service.view(WS, RUN)).rejects.toMatchObject({
      code: "repurpose/not_available",
    });
  });
});

describe("RepurposeEpisodePackService — writing it", () => {
  it("writes it once, for the latest transcript revision, in the run's language", async () => {
    const h = harness();
    await h.service.ensure(h.run);
    expect(h.insights.requestEpisodePack).toHaveBeenCalledWith({
      projectId: PROJECT,
      workspaceId: WS,
      jobKey: `${episodePackJobPrefix(PROJECT)}${TRANSCRIPT}:3`,
      copy: { language: "hi-Latn", scriptMode: "roman" },
    });
  });

  it("does not write it again while it is written, being written, or has failed", async () => {
    for (const setup of [
      { row: { id: "o1", output: PACK, createdAt: new Date() } },
      { job: { status: "running" } },
      { job: { status: "failed" } },
    ]) {
      const h = harness(setup);
      await h.service.ensure(h.run);
      expect(h.insights.requestEpisodePack).not.toHaveBeenCalled();
    }
  });

  it("writes a failed one again when the person asks", async () => {
    const h = harness({ job: { status: "failed" } });
    await h.service.write(WS, RUN);
    expect(h.insights.requestEpisodePack).toHaveBeenCalledTimes(1);
  });

  it("waits for a transcript before writing anything", async () => {
    const h = harness({ transcript: null });
    await h.service.write(WS, RUN);
    expect(h.insights.requestEpisodePack).not.toHaveBeenCalled();
  });

  it("never fails what asked for it", async () => {
    const h = harness({ requestFails: true });
    await expect(h.service.ensure(h.run)).resolves.toBeUndefined();
  });
});
