"""Tests that download or load a real model. ``RUN_SLOW=1`` to run them.

These are the only tests in the suite that touch a model rather than a fake, and
they exist to catch the class of bug a fake cannot: an adapter that parses a
hand-written response perfectly and falls over on what the library actually
returns. They run against ``worker_ai/fixtures/speech-5s/clip.wav`` — five
seconds of CC0 synthetic speech generated by ``make_clip.py`` in that directory
— because a sine tone would exercise the decode path and nothing else.

**They assert the contract, not the transcript.** The clip is speech-shaped, not
speech; no model will find words in it. What is checked is what the pipeline
depends on: the call returns, the language field is populated, the timings land
inside the clip, and the usage record is filled in. Transcript *quality* is
`09 §8`'s question and needs the hand-labelled sets of A00-05.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from worker_ai.audio import read_pcm
from worker_ai.evals.manifest import load_eval_set
from worker_ai.providers.base import TranscriptionRequest
from worker_ai.providers.local_whisper import LocalWhisperProvider

CLIP = Path(__file__).resolve().parents[1] / "worker_ai" / "fixtures" / "speech-5s" / "clip.wav"

slow = pytest.mark.skipif(
    os.environ.get("RUN_SLOW") != "1",
    reason="downloads a Whisper model; set RUN_SLOW=1",
)


def test_the_clip_ships_and_decodes() -> None:
    """Not slow: the fixture itself must be present and readable in CI."""
    assert CLIP.is_file()
    pcm = read_pcm(CLIP)
    assert pcm.sample_rate == 16_000
    assert 4_900 <= pcm.duration_ms <= 5_100


def test_the_clip_is_dedicated_to_the_public_domain() -> None:
    """A committed media file without a licence is a clearance problem later."""
    licence = (CLIP.parent / "LICENSE").read_text(encoding="utf-8")
    assert "CC0 1.0" in licence
    assert (CLIP.parent / "make_clip.py").is_file()


def test_the_clip_has_speech_and_silence_for_the_vad() -> None:
    from worker_ai.vad import EnergyVad, detect_regions

    regions = detect_regions(EnergyVad(), read_pcm(CLIP))
    assert len(regions) >= 2, "the breath gaps should split the clip"
    assert sum(region.duration_ms for region in regions) > 2_000


def test_the_vendor_replay_eval_set_points_at_the_clip() -> None:
    eval_set = load_eval_set("vendor-replay")
    assert eval_set.audio_available is True
    assert eval_set.items[0].audio is not None
    assert eval_set.items[0].audio.resolve() == CLIP.resolve()


@slow
async def test_local_whisper_decodes_the_clip_and_honours_the_contract() -> None:
    """The adapter against a real faster-whisper model, on real audio."""
    provider = LocalWhisperProvider(model_name=os.environ.get("WORKER_AI_WHISPER_MODEL", "tiny"))
    try:
        result = await provider.transcribe(
            TranscriptionRequest(audio_uri=str(CLIP), word_timestamps=True, offset_ms=1_000)
        )
    finally:
        await provider.aclose()

    assert result.language, "an adapter must always report a language"
    assert result.usage is not None
    assert result.usage.provider == "local-whisper"
    assert result.usage.cost_minor == 0
    # Whatever it heard, every timing belongs inside the chunk it was given.
    for word in result.words:
        assert 1_000 <= word.s <= word.e <= 6_100, (word.s, word.e, word.t)
    assert result.submissions[0].endpoint == "local://faster-whisper"


@slow
async def test_whisper_language_identification_runs_on_the_clip() -> None:
    """Signal 1 of the two-signal LID (D14), against a real model."""
    from worker_ai.lid import WhisperLanguageIdentifier, lid_windows

    identifier = WhisperLanguageIdentifier(
        model_name=os.environ.get("WORKER_AI_WHISPER_MODEL", "tiny")
    )
    if identifier.available() is not None:  # pragma: no cover - depends on the extra
        pytest.skip(str(identifier.available()))
    signal = await identifier.identify(str(CLIP), lid_windows(read_pcm(CLIP).duration_ms))
    # No claim about *which* language: the clip is not speech. The contract is
    # that a signal comes back at all, with a confidence in range.
    assert 0.0 <= signal.confidence <= 1.0
    assert signal.source == "whisper"
