import { screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it } from "vitest";

import { InsightsTab } from "./InsightsTab";

import { renderWithProviders } from "@/test/harness";

const PROJECT = "01JPROJECT0000000000000000";

describe("<InsightsTab />", () => {
  it("shows a loading state, then the empty state with a Generate action when there is no chapters row yet", async () => {
    renderWithProviders(<InsightsTab projectId={PROJECT} />, {
      routes: {
        [`/projects/${PROJECT}/insights`]: {
          items: [],
          disclosure: "Generated by AI from your transcript",
        },
      },
    });
    expect(await screen.findByText("No chapters yet")).toBeInTheDocument();
    expect(screen.getByTestId("insights-generate")).toBeInTheDocument();
  });

  it("shows chapters and the disclosure line once a row exists", async () => {
    renderWithProviders(<InsightsTab projectId={PROJECT} />, {
      routes: {
        [`/projects/${PROJECT}/insights`]: {
          items: [
            {
              id: "row1",
              kind: "chapters",
              templateVersion: "chapters@1",
              provider: "mock",
              region: "in",
              output: { chapters: [{ startMs: 0, title: "Intro" }] },
              usage: {},
              createdAt: "2026-01-01T00:00:00.000Z",
            },
          ],
          disclosure: "Generated by AI from your transcript",
        },
      },
    });
    expect(await screen.findByText("Intro")).toBeInTheDocument();
    expect(screen.getByTestId("insights-disclosure")).toHaveTextContent(
      "Generated by AI from your transcript",
    );
  });

  it("clicking Generate posts to /projects/{id}/insights", async () => {
    const user = userEvent.setup();
    const { fetchMock } = renderWithProviders(<InsightsTab projectId={PROJECT} />, {
      routes: {
        [`/projects/${PROJECT}/insights`]: {
          items: [],
          disclosure: "Generated by AI from your transcript",
        },
      },
    });
    await screen.findByTestId("insights-generate");
    await user.click(screen.getByTestId("insights-generate"));

    await waitFor(() => {
      const posted = fetchMock.mock.calls.some((call) => {
        const init = call[1] as RequestInit | undefined;
        return init?.method === "POST";
      });
      expect(posted).toBe(true);
    });
  });

  it("switching to the Summary tab shows its own empty state", async () => {
    const user = userEvent.setup();
    renderWithProviders(<InsightsTab projectId={PROJECT} />, {
      routes: { [`/projects/${PROJECT}/insights`]: { items: [], disclosure: "x" } },
    });
    await screen.findByTestId("insights-generate");
    await user.click(screen.getByTestId("insights-tab-summary"));
    expect(await screen.findByText("No summary yet")).toBeInTheDocument();
  });
});
