import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildMogrtStyleMap, type MogrtStyleMapping } from "./mogrt-map.js";

/**
 * Writes `docs/MOGRT-STYLE-COVERAGE.md` deterministically from
 * `buildMogrtStyleMap()`. Run after any change to `mogrt-map.ts`,
 * `classification-rules.ts`, or `packages/caption-styles/styles/*.json`.
 *
 * Run with: `pnpm --filter @montaj/premiere-uxp generate:style-coverage`
 */

function renderMarkdown(mapping: MogrtStyleMapping[]): string {
  const counts = { supported: 0, approximate: 0, unsupported: 0 };
  for (const entry of mapping) counts[entry.support]++;

  const lines: string[] = [];
  lines.push("# MOGRT style coverage (C06b, generated)");
  lines.push("");
  lines.push(
    "Generated by `pnpm --filter @montaj/premiere-uxp generate:style-coverage` from " +
      "`src/styles/mogrt-map.ts` (classification rules mirrored from C08b's " +
      "`plugins/resolve/aksharo_core_app/fusion/classification_rules.json`, see " +
      "`src/styles/classification-rules.ts`) against `packages/caption-styles/styles/*.json`. " +
      "Do not edit by hand.",
  );
  lines.push("");
  lines.push(
    `**${counts.supported} supported, ${counts.approximate} approximate, ${counts.unsupported} unsupported** of ${mapping.length} styles.`,
  );
  lines.push("");
  lines.push(
    "Every style reaches picture regardless of this table: C06's apply-modes flow uses the " +
      "pre-rendered alpha overlay path (A20) whenever a style isn't MOGRT-exact, so " +
      '*unsupported*/*approximate* here means "not a native, re-timeable MOGRT clip in the ' +
      'Premiere timeline", never "missing from the export."',
  );
  lines.push("");
  lines.push("| Style | Status | Reasons |");
  lines.push("|---|---|---|");
  for (const entry of mapping) {
    const status = entry.support.charAt(0).toUpperCase() + entry.support.slice(1);
    const reasons = entry.reasons.length > 0 ? entry.reasons.join(" ") : "—";
    lines.push(`| \`${entry.styleId}\` | ${status} | ${reasons} |`);
  }
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const mapping = buildMogrtStyleMap();
  const markdown = renderMarkdown(mapping);
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = join(here, "..", "..", "docs", "MOGRT-STYLE-COVERAGE.md");
  writeFileSync(outPath, markdown);
  console.error(`wrote ${outPath} (${mapping.length} styles)`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}

export { renderMarkdown };
