import { fireEvent, screen, waitFor, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import type { RepurposeEpisodePack, RepurposeRunView } from "@montaj/api-client";

import {
  EPISODE_PACK_COPY,
  EpisodePackPanel,
  chapterLines,
  youtubeDescriptionOf,
} from "./EpisodePackPanel";

import { renderWithProviders } from "@/test/harness";

const RUN_ID = "01JS0000000000000000000RUN";
const ROUTE = `/repurpose/runs/${RUN_ID}/episode-pack`;

const PACK: RepurposeEpisodePack = {
  chapters: [
    { startMs: 0, title: "Shuruaat" },
    { startMs: 65_000, title: "Salary ka jaal" },
    { startMs: 3_725_000, title: "Emergency fund" },
  ],
  youtubeDescription: "Is video mein salary aur savings ki baat hai.",
  showNotes: "Savings ki aadat.\n- Salary trap\n- Pehle khud ko pay karo",
  linkedinPost: "Salary badhna kaafi nahi hai. Aap kya sochte hain?",
  xThread: ["Salary se ameer kyun nahi bante?", "Kyunki kharcha bhi badhta hai."],
  newsletter: "Salary ka jaal\n\nIs hafte savings ki baat.",
  locale: "hi-Latn",
  source: "model",
};

function run(overrides: Partial<RepurposeRunView> = {}): RepurposeRunView {
  return {
    id: RUN_ID,
    workspaceId: "01JWORKSPACE00000000000000",
    sourceProjectId: "01JPROJECT0000000000000000",
    sourceKind: "upload",
    sourceDisplay: null,
    mode: "ai",
    status: "candidates_ready",
    currentStage: "finding_clips",
    progress: 55,
    stages: [],
    message: "",
    failureCode: null,
    canCancel: true,
    canRetry: false,
    candidateCount: 3,
    clipCount: 0,
    variantCount: 0,
    createdAt: "2026-09-29T10:00:00.000Z",
    updatedAt: "2026-09-29T10:00:00.000Z",
    ...overrides,
  };
}

function view(status: string, pack: RepurposeEpisodePack | null = null): Record<string, unknown> {
  return {
    runId: RUN_ID,
    status,
    pack,
    createdAt: pack === null ? null : "2026-09-29T11:00:00.000Z",
    disclosure: "Generated by AI from your transcript",
  };
}

describe("chapter times", () => {
  it("start at 0:00 for a run over the whole video", () => {
    expect(chapterLines(PACK.chapters, 0)).toEqual([
      "0:00 Shuruaat",
      "1:05 Salary ka jaal",
      "1:02:05 Emergency fund",
    ]);
  });

  it("are on the video's own clock for a run over part of it", () => {
    expect(chapterLines(PACK.chapters.slice(0, 2), 730_000)).toEqual([
      "12:10 Shuruaat",
      "13:15 Salary ka jaal",
    ]);
  });

  it("follow the description, under their heading, in what is copied for YouTube", () => {
    expect(youtubeDescriptionOf(PACK, 0)).toBe(
      "Is video mein salary aur savings ki baat hai.\n\nChapters\n0:00 Shuruaat\n1:05 Salary ka jaal\n1:02:05 Emergency fund",
    );
    expect(youtubeDescriptionOf({ ...PACK, chapters: [] }, 0)).toBe(PACK.youtubeDescription);
  });
});

describe("<EpisodePackPanel />", () => {
  it("shows every part of a written pack with its own Copy button", async () => {
    renderWithProviders(<EpisodePackPanel run={run()} />, {
      routes: { [ROUTE]: view("ready", PACK) },
    });

    const panel = await screen.findByTestId("episode-pack");
    await waitFor(() => {
      expect(panel).toHaveAttribute("data-state", "ready");
    });
    expect(panel.tagName).toBe("DETAILS");
    for (const id of ["chapters", "youtube", "show-notes", "linkedin", "x-thread", "newsletter"]) {
      expect(within(panel).getByTestId(`episode-pack-${id}`)).toBeInTheDocument();
      expect(within(panel).getByTestId(`copy-episode-${id}`)).toBeInTheDocument();
    }
    expect(within(panel).getByTestId("episode-pack-x-thread")).toHaveTextContent(
      "1/2 Salary se ameer kyun nahi bante?",
    );
    expect(within(panel).getByTestId("episode-pack-disclosure")).toHaveTextContent(
      "Generated by AI from your transcript",
    );
  });

  it("says it is being written while it is", async () => {
    renderWithProviders(<EpisodePackPanel run={run()} />, { routes: { [ROUTE]: view("writing") } });
    expect(await screen.findByTestId("episode-pack-writing")).toHaveTextContent(
      EPISODE_PACK_COPY.writing,
    );
  });

  it("offers to write it on a run whose person picks the moments", async () => {
    const { fetchMock } = renderWithProviders(<EpisodePackPanel run={run()} />, {
      routes: { [ROUTE]: view("none") },
    });

    const button = await screen.findByTestId("episode-pack-write");
    expect(button).toHaveTextContent(EPISODE_PACK_COPY.write);
    fireEvent.click(button);

    await waitFor(() => {
      const methods = fetchMock.mock.calls.map(
        ([, init]) => (init as RequestInit | undefined)?.method ?? "GET",
      );
      expect(methods).toContain("POST");
    });
  });

  it("offers to try again when it could not be written", async () => {
    renderWithProviders(<EpisodePackPanel run={run()} />, { routes: { [ROUTE]: view("failed") } });
    expect(await screen.findByTestId("episode-pack-failed")).toHaveTextContent(
      EPISODE_PACK_COPY.failed,
    );
    expect(screen.getByTestId("episode-pack-write")).toHaveTextContent(EPISODE_PACK_COPY.tryAgain);
  });

  it("tells an Autopilot run still finding moments that it comes by itself", async () => {
    renderWithProviders(
      <EpisodePackPanel run={run({ automation: "auto", status: "analyzing" })} />,
      { routes: { [ROUTE]: view("none") } },
    );
    expect(await screen.findByTestId("episode-pack-expected")).toHaveTextContent(
      EPISODE_PACK_COPY.expected,
    );
    expect(screen.queryByTestId("episode-pack-write")).not.toBeInTheDocument();
  });

  it("shows nothing before there is a transcript, or from an API without the route", async () => {
    const early = renderWithProviders(<EpisodePackPanel run={run({ status: "acquiring" })} />, {
      routes: { [ROUTE]: view("none") },
    });
    await waitFor(() => {
      expect(early.fetchMock).toHaveBeenCalled();
    });
    expect(screen.queryByTestId("episode-pack")).not.toBeInTheDocument();
    early.unmount();

    const missing = renderWithProviders(<EpisodePackPanel run={run()} />, { routes: {} });
    await waitFor(() => {
      expect(missing.fetchMock).toHaveBeenCalled();
    });
    await waitFor(() => {
      expect(screen.queryByTestId("episode-pack")).not.toBeInTheDocument();
    });
  });
});
