import { resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { loadRepoDotenv } from "../src/config/dotenv.js";

loadRepoDotenv(resolve(__dirname, ".."));

export interface SeedTrackData {
  id: string;
  title: string;
  artist: string;
  mood: "ENERGETIC" | "CHILL" | "DRAMATIC" | "CORPORATE" | "INSPIRATIONAL" | "MYSTERIOUS";
  tempo: "SLOW" | "MEDIUM" | "FAST";
  bpm: number;
  durationSec: number;
  previewUri: string;
  masterUri: string;
  waveformJson: string;
  isPublic: boolean;
}

function generateWaveform(seed: number, count: number = 60): string {
  const peaks: number[] = [];
  let prev = 0.3;
  for (let i = 0; i < count; i++) {
    // Deterministic pseudo-random variation
    const noise = Math.sin(seed * 997 + i * 13.37) * 0.5 + 0.5;
    const value = Math.max(0.08, Math.min(0.98, prev * 0.4 + noise * 0.6));
    peaks.push(Math.round(value * 100) / 100);
    prev = value;
  }
  return JSON.stringify(peaks);
}

export const SEED_TRACKS: SeedTrackData[] = [
  // --- ENERGETIC (Tech, Startup Hype, Action, High Tempo) ---
  {
    id: "track-eng-001",
    title: "Tech Cyber Pulse",
    artist: "Aksharo Originals",
    mood: "ENERGETIC",
    tempo: "FAST",
    bpm: 128,
    durationSec: 154.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/tech-cyber-pulse.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/tech-cyber-pulse.wav",
    waveformJson: generateWaveform(1),
    isPublic: true,
  },
  {
    id: "track-eng-002",
    title: "Startup Hustle Overdrive",
    artist: "Aksharo Originals",
    mood: "ENERGETIC",
    tempo: "FAST",
    bpm: 132,
    durationSec: 120.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/startup-hustle-overdrive.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/startup-hustle-overdrive.wav",
    waveformJson: generateWaveform(2),
    isPublic: true,
  },
  {
    id: "track-eng-003",
    title: "Electro Neon Glide",
    artist: "Future Wave Labs",
    mood: "ENERGETIC",
    tempo: "FAST",
    bpm: 125,
    durationSec: 142.5,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/electro-neon-glide.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/electro-neon-glide.wav",
    waveformJson: generateWaveform(3),
    isPublic: true,
  },
  {
    id: "track-eng-004",
    title: "Hyperdrive Accelerate",
    artist: "Aksharo Originals",
    mood: "ENERGETIC",
    tempo: "FAST",
    bpm: 140,
    durationSec: 110.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/hyperdrive-accelerate.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/hyperdrive-accelerate.wav",
    waveformJson: generateWaveform(4),
    isPublic: true,
  },
  {
    id: "track-eng-005",
    title: "Breakbeat Rush",
    artist: "Groove Sync",
    mood: "ENERGETIC",
    tempo: "FAST",
    bpm: 135,
    durationSec: 130.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/breakbeat-rush.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/breakbeat-rush.wav",
    waveformJson: generateWaveform(5),
    isPublic: true,
  },
  {
    id: "track-eng-006",
    title: "Future Bass Sunrise",
    artist: "Aksharo Originals",
    mood: "ENERGETIC",
    tempo: "MEDIUM",
    bpm: 118,
    durationSec: 165.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/future-bass-sunrise.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/future-bass-sunrise.wav",
    waveformJson: generateWaveform(6),
    isPublic: true,
  },
  {
    id: "track-eng-007",
    title: "Apex Velocity",
    artist: "Sonic Drive",
    mood: "ENERGETIC",
    tempo: "FAST",
    bpm: 130,
    durationSec: 145.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/apex-velocity.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/apex-velocity.wav",
    waveformJson: generateWaveform(7),
    isPublic: true,
  },
  {
    id: "track-eng-008",
    title: "Midnight Sprint",
    artist: "Aksharo Originals",
    mood: "ENERGETIC",
    tempo: "FAST",
    bpm: 126,
    durationSec: 115.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/midnight-sprint.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/midnight-sprint.wav",
    waveformJson: generateWaveform(8),
    isPublic: true,
  },
  {
    id: "track-eng-009",
    title: "Power Up Funk",
    artist: "Brass City Collective",
    mood: "ENERGETIC",
    tempo: "MEDIUM",
    bpm: 115,
    durationSec: 138.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/power-up-funk.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/power-up-funk.wav",
    waveformJson: generateWaveform(9),
    isPublic: true,
  },

  // --- CHILL (Lo-Fi, Relaxed, Ambient, Banter) ---
  {
    id: "track-chl-001",
    title: "Coffee & Code Lo-Fi",
    artist: "Aksharo Originals",
    mood: "CHILL",
    tempo: "SLOW",
    bpm: 78,
    durationSec: 180.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/coffee-and-code-lofi.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/coffee-and-code-lofi.wav",
    waveformJson: generateWaveform(10),
    isPublic: true,
  },
  {
    id: "track-chl-002",
    title: "Rainy Afternoon Vinyl",
    artist: "Dusty Needle",
    mood: "CHILL",
    tempo: "SLOW",
    bpm: 72,
    durationSec: 160.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/rainy-afternoon-vinyl.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/rainy-afternoon-vinyl.wav",
    waveformJson: generateWaveform(11),
    isPublic: true,
  },
  {
    id: "track-chl-003",
    title: "Subtle Chillhop Breeze",
    artist: "Aksharo Originals",
    mood: "CHILL",
    tempo: "MEDIUM",
    bpm: 85,
    durationSec: 140.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/subtle-chillhop-breeze.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/subtle-chillhop-breeze.wav",
    waveformJson: generateWaveform(12),
    isPublic: true,
  },
  {
    id: "track-chl-004",
    title: "Pastel Sunset Groove",
    artist: "Velvet Waves",
    mood: "CHILL",
    tempo: "MEDIUM",
    bpm: 88,
    durationSec: 155.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/pastel-sunset-groove.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/pastel-sunset-groove.wav",
    waveformJson: generateWaveform(13),
    isPublic: true,
  },
  {
    id: "track-chl-005",
    title: "Warm Acoustic Afternoon",
    artist: "Cedar Wood Sessions",
    mood: "CHILL",
    tempo: "SLOW",
    bpm: 75,
    durationSec: 148.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/warm-acoustic-afternoon.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/warm-acoustic-afternoon.wav",
    waveformJson: generateWaveform(14),
    isPublic: true,
  },
  {
    id: "track-chl-006",
    title: "Midnight Study Session",
    artist: "Aksharo Originals",
    mood: "CHILL",
    tempo: "SLOW",
    bpm: 70,
    durationSec: 172.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/midnight-study-session.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/midnight-study-session.wav",
    waveformJson: generateWaveform(15),
    isPublic: true,
  },
  {
    id: "track-chl-007",
    title: "Quirky Banter Beat",
    artist: "Aksharo Originals",
    mood: "CHILL",
    tempo: "MEDIUM",
    bpm: 92,
    durationSec: 112.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/quirky-banter-beat.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/quirky-banter-beat.wav",
    waveformJson: generateWaveform(16),
    isPublic: true,
  },
  {
    id: "track-chl-008",
    title: "Lo-Fi Lounge Echoes",
    artist: "Tape Deck Soul",
    mood: "CHILL",
    tempo: "SLOW",
    bpm: 80,
    durationSec: 168.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/lo-fi-lounge-echoes.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/lo-fi-lounge-echoes.wav",
    waveformJson: generateWaveform(17),
    isPublic: true,
  },

  // --- DRAMATIC (Cinematic Piano, Tension, Melancholy, Storytelling) ---
  {
    id: "track-drm-001",
    title: "Cinematic Piano Melancholy",
    artist: "Aksharo Originals",
    mood: "DRAMATIC",
    tempo: "SLOW",
    bpm: 68,
    durationSec: 190.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/cinematic-piano-melancholy.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/cinematic-piano-melancholy.wav",
    waveformJson: generateWaveform(18),
    isPublic: true,
  },
  {
    id: "track-drm-002",
    title: "Tension In The Shadows",
    artist: "Orchestral Noir",
    mood: "DRAMATIC",
    tempo: "SLOW",
    bpm: 74,
    durationSec: 165.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/tension-in-the-shadows.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/tension-in-the-shadows.wav",
    waveformJson: generateWaveform(19),
    isPublic: true,
  },
  {
    id: "track-drm-003",
    title: "Echoes Of The Fall",
    artist: "Aksharo Originals",
    mood: "DRAMATIC",
    tempo: "MEDIUM",
    bpm: 84,
    durationSec: 150.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/echoes-of-the-fall.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/echoes-of-the-fall.wav",
    waveformJson: generateWaveform(20),
    isPublic: true,
  },
  {
    id: "track-drm-004",
    title: "The Final Stand",
    artist: "Epic Horizon Audio",
    mood: "DRAMATIC",
    tempo: "FAST",
    bpm: 120,
    durationSec: 140.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/the-final-stand.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/the-final-stand.wav",
    waveformJson: generateWaveform(21),
    isPublic: true,
  },
  {
    id: "track-drm-005",
    title: "Solitary Reflection",
    artist: "Aksharo Originals",
    mood: "DRAMATIC",
    tempo: "SLOW",
    bpm: 65,
    durationSec: 185.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/solitary-reflection.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/solitary-reflection.wav",
    waveformJson: generateWaveform(22),
    isPublic: true,
  },
  {
    id: "track-drm-006",
    title: "Heartbeat Suspense",
    artist: "Dark Pulse Studio",
    mood: "DRAMATIC",
    tempo: "SLOW",
    bpm: 72,
    durationSec: 135.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/heartbeat-suspense.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/heartbeat-suspense.wav",
    waveformJson: generateWaveform(23),
    isPublic: true,
  },
  {
    id: "track-drm-007",
    title: "Rising Stakes",
    artist: "Aksharo Originals",
    mood: "DRAMATIC",
    tempo: "MEDIUM",
    bpm: 96,
    durationSec: 145.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/rising-stakes.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/rising-stakes.wav",
    waveformJson: generateWaveform(24),
    isPublic: true,
  },
  {
    id: "track-drm-008",
    title: "Thunderous Crescendo",
    artist: "Titan Symphony",
    mood: "DRAMATIC",
    tempo: "FAST",
    bpm: 124,
    durationSec: 155.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/thunderous-crescendo.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/thunderous-crescendo.wav",
    waveformJson: generateWaveform(25),
    isPublic: true,
  },

  // --- CORPORATE (Clean, Upbeat, Professional, Explainer, Tech) ---
  {
    id: "track-crp-001",
    title: "Silicon Valley Optimism",
    artist: "Aksharo Originals",
    mood: "CORPORATE",
    tempo: "MEDIUM",
    bpm: 110,
    durationSec: 135.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/silicon-valley-optimism.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/silicon-valley-optimism.wav",
    waveformJson: generateWaveform(26),
    isPublic: true,
  },
  {
    id: "track-crp-002",
    title: "Modern Tech Explainer",
    artist: "Bright Wave Media",
    mood: "CORPORATE",
    tempo: "MEDIUM",
    bpm: 116,
    durationSec: 125.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/modern-tech-explainer.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/modern-tech-explainer.wav",
    waveformJson: generateWaveform(27),
    isPublic: true,
  },
  {
    id: "track-crp-003",
    title: "Clean Corporate Presentation",
    artist: "Aksharo Originals",
    mood: "CORPORATE",
    tempo: "MEDIUM",
    bpm: 105,
    durationSec: 140.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/clean-corporate-presentation.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/clean-corporate-presentation.wav",
    waveformJson: generateWaveform(28),
    isPublic: true,
  },
  {
    id: "track-crp-004",
    title: "Forward Momentum",
    artist: "Elevate Sound",
    mood: "CORPORATE",
    tempo: "FAST",
    bpm: 122,
    durationSec: 130.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/forward-momentum.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/forward-momentum.wav",
    waveformJson: generateWaveform(29),
    isPublic: true,
  },
  {
    id: "track-crp-005",
    title: "Minimalist Acoustic Drive",
    artist: "Aksharo Originals",
    mood: "CORPORATE",
    tempo: "MEDIUM",
    bpm: 108,
    durationSec: 150.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/minimalist-acoustic-drive.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/minimalist-acoustic-drive.wav",
    waveformJson: generateWaveform(30),
    isPublic: true,
  },
  {
    id: "track-crp-006",
    title: "Data Flow Rhythm",
    artist: "Digital Frontier",
    mood: "CORPORATE",
    tempo: "MEDIUM",
    bpm: 112,
    durationSec: 144.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/data-flow-rhythm.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/data-flow-rhythm.wav",
    waveformJson: generateWaveform(31),
    isPublic: true,
  },
  {
    id: "track-crp-007",
    title: "Product Showcase Glow",
    artist: "Aksharo Originals",
    mood: "CORPORATE",
    tempo: "SLOW",
    bpm: 95,
    durationSec: 138.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/product-showcase-glow.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/product-showcase-glow.wav",
    waveformJson: generateWaveform(32),
    isPublic: true,
  },
  {
    id: "track-crp-008",
    title: "Strategic Vision",
    artist: "Clearwater Audio",
    mood: "CORPORATE",
    tempo: "MEDIUM",
    bpm: 102,
    durationSec: 160.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/strategic-vision.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/strategic-vision.wav",
    waveformJson: generateWaveform(33),
    isPublic: true,
  },

  // --- INSPIRATIONAL (Uplifting, Cinematic, Motivational, Journey) ---
  {
    id: "track-ins-001",
    title: "Sunrise Over The Peaks",
    artist: "Aksharo Originals",
    mood: "INSPIRATIONAL",
    tempo: "MEDIUM",
    bpm: 98,
    durationSec: 162.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/sunrise-over-the-peaks.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/sunrise-over-the-peaks.wav",
    waveformJson: generateWaveform(34),
    isPublic: true,
  },
  {
    id: "track-ins-002",
    title: "Unstoppable Dreamer",
    artist: "Aurora Skies",
    mood: "INSPIRATIONAL",
    tempo: "FAST",
    bpm: 122,
    durationSec: 145.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/unstoppable-dreamer.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/unstoppable-dreamer.wav",
    waveformJson: generateWaveform(35),
    isPublic: true,
  },
  {
    id: "track-ins-003",
    title: "Beyond The Horizon",
    artist: "Aksharo Originals",
    mood: "INSPIRATIONAL",
    tempo: "MEDIUM",
    bpm: 104,
    durationSec: 175.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/beyond-the-horizon.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/beyond-the-horizon.wav",
    waveformJson: generateWaveform(36),
    isPublic: true,
  },
  {
    id: "track-ins-004",
    title: "Triumph Of The Spirit",
    artist: "Crest Symphony",
    mood: "INSPIRATIONAL",
    tempo: "FAST",
    bpm: 126,
    durationSec: 150.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/triumph-of-the-spirit.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/triumph-of-the-spirit.wav",
    waveformJson: generateWaveform(37),
    isPublic: true,
  },
  {
    id: "track-ins-005",
    title: "A Hero's Awakening",
    artist: "Aksharo Originals",
    mood: "INSPIRATIONAL",
    tempo: "SLOW",
    bpm: 78,
    durationSec: 180.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/a-heros-awakening.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/a-heros-awakening.wav",
    waveformJson: generateWaveform(38),
    isPublic: true,
  },
  {
    id: "track-ins-006",
    title: "Infinite Hope",
    artist: "Luminary Sound",
    mood: "INSPIRATIONAL",
    tempo: "MEDIUM",
    bpm: 92,
    durationSec: 158.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/infinite-hope.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/infinite-hope.wav",
    waveformJson: generateWaveform(39),
    isPublic: true,
  },
  {
    id: "track-ins-007",
    title: "Ascent To Glory",
    artist: "Aksharo Originals",
    mood: "INSPIRATIONAL",
    tempo: "FAST",
    bpm: 128,
    durationSec: 135.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/ascent-to-glory.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/ascent-to-glory.wav",
    waveformJson: generateWaveform(40),
    isPublic: true,
  },
  {
    id: "track-ins-008",
    title: "Kindred Spirits",
    artist: "Acoustic Ember",
    mood: "INSPIRATIONAL",
    tempo: "SLOW",
    bpm: 82,
    durationSec: 142.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/kindred-spirits.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/kindred-spirits.wav",
    waveformJson: generateWaveform(41),
    isPublic: true,
  },

  // --- MYSTERIOUS (Investigative, Deep Bass, Enigmatic, Thriller) ---
  {
    id: "track-mys-001",
    title: "Subterranean Whispers",
    artist: "Aksharo Originals",
    mood: "MYSTERIOUS",
    tempo: "SLOW",
    bpm: 70,
    durationSec: 170.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/subterranean-whispers.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/subterranean-whispers.wav",
    waveformJson: generateWaveform(42),
    isPublic: true,
  },
  {
    id: "track-mys-002",
    title: "Digital Noir Investigation",
    artist: "Cipher Soundworks",
    mood: "MYSTERIOUS",
    tempo: "SLOW",
    bpm: 76,
    durationSec: 148.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/digital-noir-investigation.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/digital-noir-investigation.wav",
    waveformJson: generateWaveform(43),
    isPublic: true,
  },
  {
    id: "track-mys-003",
    title: "The Unsolved Mystery",
    artist: "Aksharo Originals",
    mood: "MYSTERIOUS",
    tempo: "MEDIUM",
    bpm: 88,
    durationSec: 160.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/the-unsolved-mystery.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/the-unsolved-mystery.wav",
    waveformJson: generateWaveform(44),
    isPublic: true,
  },
  {
    id: "track-mys-004",
    title: "Curious Clockwork",
    artist: "Enigma Works",
    mood: "MYSTERIOUS",
    tempo: "MEDIUM",
    bpm: 94,
    durationSec: 130.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/curious-clockwork.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/curious-clockwork.wav",
    waveformJson: generateWaveform(45),
    isPublic: true,
  },
  {
    id: "track-mys-005",
    title: "Midnight Deep Intrigue",
    artist: "Aksharo Originals",
    mood: "MYSTERIOUS",
    tempo: "SLOW",
    bpm: 68,
    durationSec: 175.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/midnight-deep-intrigue.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/midnight-deep-intrigue.wav",
    waveformJson: generateWaveform(46),
    isPublic: true,
  },
  {
    id: "track-mys-006",
    title: "Labyrinth In The Dark",
    artist: "Phantom Frequency",
    mood: "MYSTERIOUS",
    tempo: "SLOW",
    bpm: 74,
    durationSec: 155.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/labyrinth-in-the-dark.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/labyrinth-in-the-dark.wav",
    waveformJson: generateWaveform(47),
    isPublic: true,
  },
  {
    id: "track-mys-007",
    title: "Quantum Riddle",
    artist: "Aksharo Originals",
    mood: "MYSTERIOUS",
    tempo: "MEDIUM",
    bpm: 90,
    durationSec: 142.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/quantum-riddle.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/quantum-riddle.wav",
    waveformJson: generateWaveform(48),
    isPublic: true,
  },
  {
    id: "track-mys-008",
    title: "Whispering Fog",
    artist: "Ghost Tone Studio",
    mood: "MYSTERIOUS",
    tempo: "SLOW",
    bpm: 66,
    durationSec: 165.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/whispering-fog.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/whispering-fog.wav",
    waveformJson: generateWaveform(49),
    isPublic: true,
  },
  {
    id: "track-mys-009",
    title: "Secret Code Decoder",
    artist: "Aksharo Originals",
    mood: "MYSTERIOUS",
    tempo: "MEDIUM",
    bpm: 86,
    durationSec: 138.0,
    previewUri: "https://cdn.aksharo.com/audio/music/previews/secret-code-decoder.mp3",
    masterUri: "https://cdn.aksharo.com/audio/music/masters/secret-code-decoder.wav",
    waveformJson: generateWaveform(50),
    isPublic: true,
  },
];

export async function seedMusicTracks(prisma: PrismaClient): Promise<number> {
  let seededCount = 0;
  for (const track of SEED_TRACKS) {
    await prisma.musicTrack.upsert({
      where: { id: track.id },
      create: {
        id: track.id,
        title: track.title,
        artist: track.artist,
        mood: track.mood,
        tempo: track.tempo,
        bpm: track.bpm,
        durationSec: track.durationSec,
        previewUri: track.previewUri,
        masterUri: track.masterUri,
        waveformJson: track.waveformJson,
        isPublic: track.isPublic,
      },
      update: {
        title: track.title,
        artist: track.artist,
        mood: track.mood,
        tempo: track.tempo,
        bpm: track.bpm,
        durationSec: track.durationSec,
        previewUri: track.previewUri,
        masterUri: track.masterUri,
        waveformJson: track.waveformJson,
        isPublic: track.isPublic,
      },
    });
    seededCount++;
  }
  return seededCount;
}

if (process.argv[1] && process.argv[1].includes("seed-music")) {
  const prisma = new PrismaClient();
  seedMusicTracks(prisma)
    .then((count) => {
      console.log(`[seed-music] Successfully seeded ${count} royalty-free music tracks.`);
      return prisma.$disconnect();
    })
    .catch((err) => {
      console.error("[seed-music] Error seeding music tracks:", err);
      return prisma.$disconnect().finally(() => process.exit(1));
    });
}
