/**
 * `toAss` — StyleDoc v2 + a projection → an ASS v4+ document.
 *
 * `.ass` is a sidecar format only (D33): nothing here is ever the burned-in
 * path. `assExportable` is true whenever a readable sidecar can be produced at
 * all (always, in this implementation — every StyleDoc field maps to *some*
 * ASS primitive); `assRenderable` is never decided here — only the parity gate
 * (`parity/`) may set that flag, by actually rendering the output through
 * libass and diffing it against the Skia render (D33).
 */

import type { StyleDoc } from "@montaj/caption-styles";

import { buildSegmentEvents } from "./events.js";
import { buildStyleLine, STYLE_FORMAT } from "./style-map.js";
import {
  styleFromCatalogue,
  type AssProjection,
  type AssStyleCatalogue,
  type AssTranscript,
  type ToAssOptions,
} from "./types.js";

import type { AssWarning } from "./capabilities.js";

export type { AssWarning, AssWarningCode } from "./capabilities.js";
export type {
  AssCanvas,
  AssProjection,
  AssSegment,
  AssStyleCatalogue,
  AssTranscript,
  AssWord,
  ToAssOptions,
} from "./types.js";

export interface ToAssResult {
  /** The complete `.ass` document. */
  readonly ass: string;
  readonly warnings: readonly AssWarning[];
  /** Style ids actually used, in the order their `Style:` lines were written. */
  readonly stylesUsed: readonly string[];
}

const SCRIPT_INFO_HEADER = (canvas: { width: number; height: number }): string =>
  [
    "[Script Info]",
    "; Generated by @montaj/ass-exporter (A18a) — do not edit by hand.",
    "Title: Montaj export",
    "ScriptType: v4.00+",
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    "YCbCr Matrix: TV.709",
    `PlayResX: ${String(canvas.width)}`,
    `PlayResY: ${String(canvas.height)}`,
    "",
  ].join("\n");

/**
 * Builds the ASS document. Synchronous and pure: no filesystem, no shaper —
 * `\pos` comes from the StyleDoc's own layout anchor (`events.ts`), not from a
 * HarfBuzz layout pass, so the whole export is one function call.
 */
export function toAss(
  projection: AssProjection,
  transcript: AssTranscript,
  styleCatalogue: AssStyleCatalogue,
  canvas: { readonly width: number; readonly height: number } = projection.canvas,
  opts: ToAssOptions = {},
): ToAssResult {
  const effectiveCanvas = opts.canvas ?? canvas ?? projection.canvas;
  const warnings: AssWarning[] = [];
  const usedStyles = new Map<string, StyleDoc>();
  const eventLines: string[] = [];

  const bySeq = [...projection.segments].sort((a, b) => {
    if (a.seq !== undefined && b.seq !== undefined) return a.seq.localeCompare(b.seq, "en");
    return a.startMs - b.startMs;
  });

  for (const segment of bySeq) {
    const style = styleFromCatalogue(styleCatalogue, segment.styleRef, opts.defaultStyleId);
    if (style === undefined) {
      warnings.push({
        code: "effect_only_style",
        message: `segment ${segment.id} references an unresolved style (${segment.styleRef ?? "<default>"}); skipped`,
        context: segment.id,
      });
      continue;
    }
    usedStyles.set(style.id, style);
    const events = buildSegmentEvents(
      segment,
      style,
      transcript,
      { ...opts, canvas: effectiveCanvas },
      warnings,
    );
    for (const event of events) eventLines.push(event.line);
  }

  const styleLines = [...usedStyles.values()].map(
    (style) => buildStyleLine(style, effectiveCanvas).line,
  );

  const doc = [
    SCRIPT_INFO_HEADER(effectiveCanvas),
    "[V4+ Styles]",
    STYLE_FORMAT,
    ...styleLines,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ...eventLines,
    "",
  ].join("\n");

  return { ass: doc, warnings, stylesUsed: [...usedStyles.keys()] };
}
