import { HttpStatus, Injectable, Logger } from "@nestjs/common";

import type { Segment, TranscriptChunk } from "@montaj/edg/schemas";
import type { PromptTranscriptInput, InsightKind } from "@montaj/prompts";

import {
  INSIGHTS_MAX_CHUNK_PAGES,
  INSIGHTS_TRANSCRIPT_CHUNK_PAGE_LIMIT,
} from "./insights.errors.js";
import { quoteInsight } from "./insights.quote.js";
import { InsightsRepository } from "./insights.repository.js";
import { AppException, ERROR_CODES } from "../common/errors/error-codes.js";
import { PrismaService } from "../common/prisma/prisma.service.js";
import { EdgRepository } from "../edg/index.js";
import { JobsService } from "../jobs/jobs.service.js";
import { TranscriptsService } from "../transcripts/transcripts.service.js";

import type { LlmOutput, Project } from "@prisma/client";

/**
 * The insights feature (B11, F-206/F-207): `POST /projects/{id}/insights`
 * enqueues one `ai.llm` job per requested kind, `GET` reads the latest
 * `llm_outputs` row per kind.
 *
 * ### PII minimisation (brief §2)
 *
 * The job payload built here carries exactly `{language, mediaTitle,
 * durationMs, segments[{startMs,endMs,text,speaker}]}` — transcript text and
 * the project's own title, never a user id, email or name. `speaker` is the
 * diarisation label (`"spk0"`), not an identity.
 *
 * ### Tenancy
 *
 * Same rule as `TranscriptsService`: a project in another workspace is a 404,
 * never a 403 (THREAT-MODEL T4, T5).
 */
export interface RequestInsightsInput {
  readonly projectId: string;
  readonly workspaceId: string;
  readonly kinds: readonly InsightKind[];
  readonly tone?: string;
  readonly regenerate?: boolean;
}

export interface InsightJobAccepted {
  readonly kind: InsightKind;
  readonly jobId: string;
  readonly deduplicated: boolean;
  readonly tenths: number;
}

export interface InsightsAccepted {
  readonly jobs: readonly InsightJobAccepted[];
  readonly totalTenths: number;
}

export const INSIGHTS_DISCLOSURE = "Generated by AI from your transcript";

@Injectable()
export class InsightsService {
  private readonly logger = new Logger(InsightsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly jobs: JobsService,
    private readonly transcripts: TranscriptsService,
    private readonly repository: InsightsRepository,
    private readonly edgRepository: EdgRepository,
  ) {}

  async request(input: RequestInsightsInput): Promise<InsightsAccepted> {
    const project = await this.project(input.projectId, input.workspaceId);
    const region = await this.regionOf(input.workspaceId);
    const transcript = await this.buildTranscriptInput(
      input.projectId,
      input.workspaceId,
      project.title,
    );

    const jobs: InsightJobAccepted[] = [];
    let totalTenths = 0;
    for (const kind of input.kinds) {
      const quote = quoteInsight(kind);
      const jobKey =
        input.regenerate === true
          ? `ai.llm:${kind}:${project.id}:${String(Date.now())}`
          : `ai.llm:${kind}:${project.id}`;

      const { job, deduplicated } = await this.jobs.enqueue({
        type: "ai.llm",
        workspaceId: input.workspaceId,
        projectId: project.id,
        jobKey,
        worstCaseTenths: quote.tenths,
        reason: quote.reason,
        params: {
          kind,
          region,
          transcript,
          ...(input.tone === undefined ? {} : { tone: input.tone }),
        },
      });

      jobs.push({ kind, jobId: job.id, deduplicated, tenths: quote.tenths });
      totalTenths += quote.tenths;
    }

    this.logger.log(
      { projectId: project.id, kinds: input.kinds, totalTenths },
      "insights requested",
    );

    return { jobs, totalTenths };
  }

  async list(projectId: string, workspaceId: string): Promise<LlmOutput[]> {
    await this.project(projectId, workspaceId);
    return this.repository.latestPerKind(projectId);
  }

  // -------------------------------------------------------------------------

  private async project(projectId: string, workspaceId: string): Promise<Project> {
    const project = await this.prisma.project.findFirst({
      where: { id: projectId, workspaceId, deletedAt: null },
    });
    if (project === null) {
      throw new AppException(ERROR_CODES.notFound, "No such project.", HttpStatus.NOT_FOUND);
    }
    return project;
  }

  private async regionOf(workspaceId: string): Promise<string> {
    const workspace = await this.prisma.workspace.findUnique({
      where: { id: workspaceId },
      select: { region: true },
    });
    // A workspace that resolved through WorkspaceMemberGuard always exists;
    // `in` is the platform default (`schema.prisma`'s `Region.in`) and never
    // reached in practice.
    return workspace?.region ?? "in";
  }

  /**
   * The prompt transcript (brief §3): built from the project's EDG caption
   * segments when it has one — `startWordId`/`endWordId` resolved to text
   * through {@link EdgRepository.projectionOf} and `loadChunks`, so the
   * templates see what the creator actually kept (cuts, re-segmentation and
   * text edits already applied), not the raw ASR output. A project that has
   * not been segmented into an EDG document yet (brief B11b ruling 3) falls
   * back to {@link buildTranscriptInputFromChunks}, the original raw-chunk
   * path.
   */
  private async buildTranscriptInput(
    projectId: string,
    workspaceId: string,
    mediaTitle: string,
  ): Promise<PromptTranscriptInput> {
    const project = await this.prisma.project.findFirst({
      where: { id: projectId, workspaceId, deletedAt: null },
      select: { edgDocument: { select: { id: true } } },
    });
    const edgId = project?.edgDocument?.id;
    if (edgId !== undefined) {
      const fromEdg = await this.buildTranscriptInputFromEdg(edgId, mediaTitle);
      if (fromEdg !== null) return fromEdg;
    }
    return this.buildTranscriptInputFromChunks(projectId, workspaceId, mediaTitle);
  }

  /**
   * The EDG path: resolve every live segment's `startWordId`/`endWordId` to
   * text via the document's transcript chunks. `null` when the document has
   * no live segments yet (e.g. initialised but not yet split), so the caller
   * falls back to the chunk path rather than sending the templates nothing.
   */
  private async buildTranscriptInputFromEdg(
    edgId: string,
    mediaTitle: string,
  ): Promise<PromptTranscriptInput | null> {
    const edg = await this.edgRepository.projectionOf(edgId);
    if (edg.segments.length === 0) return null;

    const chunks = await this.edgRepository.loadChunks(edg.transcript.transcriptId);
    const words = wordIndexOf(chunks);

    const segments = edg.segments
      .map((segment) => segmentFromEdg(segment, words))
      .filter((segment) => segment.text !== "");
    if (segments.length === 0) return null;

    const durationMs = Math.max(0, ...chunks.map((chunk) => chunk.endMs));

    return {
      language: edg.transcript.language,
      mediaTitle,
      durationMs,
      segments,
    };
  }

  /**
   * Reads every transcript chunk page (the original, pre-EDG path) and
   * reduces it to the language-agnostic shape the template registry and the
   * worker share. Capped at {@link INSIGHTS_MAX_CHUNK_PAGES} pages as a
   * runaway-loop guard; a project with more than that (several hours of
   * chunks) is not a realistic input for these templates in the first place.
   */
  private async buildTranscriptInputFromChunks(
    projectId: string,
    workspaceId: string,
    mediaTitle: string,
  ): Promise<PromptTranscriptInput> {
    const segments: PromptTranscriptInput["segments"][number][] = [];
    let language = "en";
    let durationMs = 0;
    let cursor: number | undefined;
    for (let page = 0; page < INSIGHTS_MAX_CHUNK_PAGES; page += 1) {
      const result = await this.transcripts.chunks({
        projectId,
        workspaceId,
        limit: INSIGHTS_TRANSCRIPT_CHUNK_PAGE_LIMIT,
        ...(cursor === undefined ? {} : { cursor }),
      });
      language = result.transcript.language;
      durationMs = Math.max(durationMs, result.transcript.durationMs);
      for (const chunk of result.chunks) segments.push(segmentOf(chunk));
      if (result.nextCursor === null) break;
      cursor = result.nextCursor;
    }

    return {
      language,
      mediaTitle,
      durationMs,
      segments,
    };
  }
}

function segmentOf(chunk: TranscriptChunk): PromptTranscriptInput["segments"][number] {
  const words = chunk.words.filter((word) => word.deleted !== true);
  const text = words
    .map((word) => word.t)
    .join(" ")
    .trim();
  const speaker = words.find((word) => word.sp !== undefined)?.sp;
  return {
    startMs: chunk.startMs,
    endMs: chunk.endMs,
    text,
    ...(speaker === undefined ? {} : { speaker }),
  };
}

/** Every live word, in document order, keyed by `wid` for O(1) boundary lookups. */
function wordIndexOf(chunks: readonly TranscriptChunk[]): {
  order: readonly string[];
  byId: ReadonlyMap<string, TranscriptChunk["words"][number]>;
} {
  const ordered = [...chunks].sort((left, right) => left.chunkIdx - right.chunkIdx);
  const order: string[] = [];
  const byId = new Map<string, TranscriptChunk["words"][number]>();
  for (const chunk of ordered) {
    for (const word of chunk.words) {
      order.push(word.wid);
      byId.set(word.wid, word);
    }
  }
  return { order, byId };
}

/**
 * One EDG segment's `startWordId..endWordId` span, resolved to plain text.
 * Deleted words are dropped, same as the chunk path's `segmentOf`; an
 * unresolvable boundary (a word id the loaded chunk window does not carry)
 * yields an empty-text segment, which the caller filters out.
 */
function segmentFromEdg(
  segment: Segment,
  words: { order: readonly string[]; byId: ReadonlyMap<string, TranscriptChunk["words"][number]> },
): PromptTranscriptInput["segments"][number] {
  const startIndex = words.order.indexOf(segment.startWordId);
  const endIndex = words.order.indexOf(segment.endWordId);
  const span =
    startIndex < 0 || endIndex < startIndex
      ? []
      : words.order
          .slice(startIndex, endIndex + 1)
          .map((wid) => words.byId.get(wid))
          .filter((word): word is TranscriptChunk["words"][number] => word !== undefined)
          .filter((word) => word.deleted !== true);

  const text = span
    .map((word) => word.t)
    .join(" ")
    .trim();
  const speaker = span.find((word) => word.sp !== undefined)?.sp;

  return {
    startMs: segment.startMs,
    endMs: segment.endMs,
    text,
    ...(speaker === undefined ? {} : { speaker }),
  };
}
