"""Edit passes: ``autocut`` (B18). ``zoom``/``reframe`` (B19) land alongside it here."""

from __future__ import annotations

from worker_ai.passes.autocut import (
    AutocutInput,
    AutocutResult,
    CutCandidate,
    Lexicon,
    LexiconEntry,
    Preset,
    SpeechRegion,
    Word,
    load_lexicon,
    run_autocut,
)
from worker_ai.passes.reframe import (
    ReframeKeyframeRow,
    ReframeResult,
    build_reframe_track,
    clamp_crop_window,
    rdp_simplify,
)
from worker_ai.passes.scenes import (
    FrameStat,
    SceneBoundary,
    detect_scenes,
    frame_stat_from_hsv,
    scene_ranges,
)
from worker_ai.passes.text_fx import (
    MAX_PER_WINDOW,
    MIN_GAP_MS,
    RATE_LIMIT_WINDOW_MS,
    TextFxEvent,
    build_text_fx_events,
    classify_intent,
)
from worker_ai.passes.text_fx import (
    Word as TextFxWord,
)
from worker_ai.passes.tracking import (
    BrightBlobDetector,
    Detection,
    FrameDetector,
    IouTracker,
    OneEuroFilter,
    SubjectPoint,
    iou,
    track_subject,
)
from worker_ai.passes.zoom import (
    ZOOM_PRESETS,
    Cue,
    CueKind,
    ZoomEvent,
    ZoomKeyframeRow,
    ZoomPreset,
    build_zoom_events,
    detect_energy_cues,
    detect_sentence_start_cues,
    ease_out_cubic,
)

__all__ = [
    "MAX_PER_WINDOW",
    "MIN_GAP_MS",
    "RATE_LIMIT_WINDOW_MS",
    "ZOOM_PRESETS",
    "AutocutInput",
    "AutocutResult",
    "BrightBlobDetector",
    "Cue",
    "CueKind",
    "CutCandidate",
    "Detection",
    "FrameDetector",
    "FrameStat",
    "IouTracker",
    "Lexicon",
    "LexiconEntry",
    "OneEuroFilter",
    "Preset",
    "ReframeKeyframeRow",
    "ReframeResult",
    "SceneBoundary",
    "SpeechRegion",
    "SubjectPoint",
    "TextFxEvent",
    "TextFxWord",
    "Word",
    "ZoomEvent",
    "ZoomKeyframeRow",
    "ZoomPreset",
    "build_reframe_track",
    "build_text_fx_events",
    "build_zoom_events",
    "clamp_crop_window",
    "classify_intent",
    "detect_energy_cues",
    "detect_scenes",
    "detect_sentence_start_cues",
    "ease_out_cubic",
    "frame_stat_from_hsv",
    "iou",
    "load_lexicon",
    "rdp_simplify",
    "run_autocut",
    "scene_ranges",
    "track_subject",
]
