from __future__ import annotations

from pathlib import Path

import pytest

from aksharo_core_app.fusion.macro import (
    MACRO_FILENAME,
    KeyframeTrack,
    MacroDefaults,
    MacroFormatError,
    defaults_from_macro,
    fusion_macro_available,
    generate_default_macro,
    generate_macro,
    macro_path,
    parse_macro,
)

GOLDEN_PATH = Path(__file__).parent / "fixtures" / "AksharoCaption.setting.golden"


def test_default_macro_matches_golden_file() -> None:
    """Regenerated by `scripts/generate_macro.py`; drift here means either the
    generator changed on purpose (update the golden) or by accident."""
    assert generate_default_macro() == GOLDEN_PATH.read_text(encoding="utf-8")


def test_installed_macro_file_matches_the_generator() -> None:
    """`AksharoCaption.setting` is a generated, committed artefact (the file
    C10's installer copies into Fusion's Macros folder) — it must never drift
    from what `generate_default_macro()` produces."""
    assert macro_path().read_text(encoding="utf-8") == generate_default_macro()


def test_fusion_macro_available_true_when_installed() -> None:
    assert fusion_macro_available() is True


def test_fusion_macro_available_false_when_missing(tmp_path: Path) -> None:
    assert fusion_macro_available(tmp_path / "missing.setting") is False


@pytest.mark.parametrize(
    "defaults",
    [
        MacroDefaults(style_id="default"),
        MacroDefaults(
            style_id="bold-drop",
            text="hello world",
            font="Anton",
            size=0.068,
            colour=(1.0, 1.0, 1.0, 1.0),
            stroke_colour=(0.043, 0.043, 0.059, 1.0),
            stroke_width=0.08,
            shadow_opacity=0.6,
            position_y=0.52,
            highlight_colour=(1.0, 0.831, 0.0, 1.0),
            highlight_start=KeyframeTrack(((0, 0.0), (12, 1.0), (30, 0.0))),
            highlight_end=KeyframeTrack(((0, 0.0), (12, 1.0))),
        ),
        MacroDefaults(style_id="no-keyframes-needed", text=""),
        MacroDefaults(style_id='quote with "escapes" and \\backslash', text='say "hi"'),
    ],
)
def test_generate_then_parse_round_trips(defaults: MacroDefaults) -> None:
    text = generate_macro(defaults)
    parsed = defaults_from_macro(text)
    assert parsed == defaults
    # Regenerating from the parsed defaults reproduces byte-identical text.
    assert generate_macro(parsed) == text


def test_parse_macro_rejects_text_outside_the_subset() -> None:
    with pytest.raises(MacroFormatError):
        parse_macro("not valid { at all")


def test_parse_macro_rejects_unterminated_table() -> None:
    with pytest.raises(MacroFormatError):
        parse_macro("Composition { Tools = {")


def test_keyframe_track_rejects_non_increasing_frames() -> None:
    with pytest.raises(ValueError, match="strictly increasing"):
        KeyframeTrack(points=((5, 0.0), (5, 1.0)))
    with pytest.raises(ValueError, match="strictly increasing"):
        KeyframeTrack(points=((10, 0.0), (5, 1.0)))


def test_macro_filename_matches_tool_name() -> None:
    assert MACRO_FILENAME == "AksharoCaption.setting"
