"""Highlight discovery (Wave 4): the ``ai.highlights@1`` contract and its parts.

- ``contracts`` - the schema mirror of ``packages/repurpose-contracts``;
- ``windows`` - sentence units and candidate windows over the whole transcript,
  and the spread-aware choice between them;
- ``scoring`` - the content signals a window is scored on;
- ``text`` - sentence ends in Latin and Devanagari, titles and excerpts.

The processor that puts them together is ``worker_ai.processors.highlights``.
"""

from __future__ import annotations

from worker_ai.highlights.acoustic import (
    AcousticEmotionAggregator,
    AcousticFeatures,
    AudioEventSpan,
    SpectralYamnetDetector,
    WindowAcousticFeatures,
    YamnetBackend,
    YamnetEventResult,
    YamnetOnnxDetector,
    analyze_pcm_window,
    analyze_wav_window,
    extract_pitch_track_yin,
    extract_window_acoustic_features,
    extract_yamnet_patches,
    load_yamnet_detector,
)
from worker_ai.highlights.contracts import (
    HIGHLIGHTS_SCHEMA_VERSION,
    MAX_DURATION_MS,
    MIN_DURATION_MS,
    DiagnosticItem,
    HighlightProposal,
    HighlightsOptions,
    HighlightsPayload,
    HighlightsResult,
    NativeChapter,
    ProposalReason,
    ScoreBreakdown,
    StorageObject,
    ViralityDiagnostic,
    highlights_job_key,
)
from worker_ai.highlights.sponsors import (
    COMMERCIAL_SCORE_THRESHOLD,
    CommercialClassification,
    classify_commercial_intent,
    commercial_score,
    detect_intro_teasers,
    fetch_sponsorblock_segments_py,
    filter_commercial_windows,
    is_commercial_segment,
)
from worker_ai.highlights.texttiling import (
    TextTileBoundary,
    TextTilingConfig,
    TextTilingResult,
    compute_texttiling,
    discourse_coherence_bonus,
)
from worker_ai.highlights.topic_search import (
    EMBEDDING_DIM,
    SEMANTIC_PREFILTER_RATIO,
    SEMANTIC_SIMILARITY_FLOOR,
    TopicIntent,
    WindowTopicMatch,
    cosine_similarity,
    embed_text,
    embed_units,
    filter_candidates_by_topic_semantics,
    parse_topic_intent,
    prefilter_candidates_for_topic,
    score_windows_for_topic,
)
from worker_ai.highlights.tribe_client import (
    NeuralAttentionScore,
    TribeClient,
    TribeWindowInput,
)
from worker_ai.highlights.windows import (
    DISALLOWED_CLOSINGS,
    DISALLOWED_OPENINGS,
    DURATION_BINS_MS,
    Unit,
    Window,
    Word,
    build_units,
    discourse_opening_advance,
    enumerate_windows,
    filter_windows_by_duration,
    is_incomplete_closing,
    padded_windows,
    snap_to_silence,
    snap_to_silence_ms,
    snap_window_to_silence,
    snap_windows,
    words_to_silence_gaps,
)

__all__ = [
    "COMMERCIAL_SCORE_THRESHOLD",
    "DISALLOWED_CLOSINGS",
    "DISALLOWED_OPENINGS",
    "DURATION_BINS_MS",
    "EMBEDDING_DIM",
    "HIGHLIGHTS_SCHEMA_VERSION",
    "MAX_DURATION_MS",
    "MIN_DURATION_MS",
    "SEMANTIC_PREFILTER_RATIO",
    "SEMANTIC_SIMILARITY_FLOOR",
    "AcousticEmotionAggregator",
    "AcousticFeatures",
    "AudioEventSpan",
    "CommercialClassification",
    "DiagnosticItem",
    "HighlightProposal",
    "HighlightsOptions",
    "HighlightsPayload",
    "HighlightsResult",
    "NativeChapter",
    "NeuralAttentionScore",
    "ProposalReason",
    "ScoreBreakdown",
    "SpectralYamnetDetector",
    "StorageObject",
    "TextTileBoundary",
    "TextTilingConfig",
    "TextTilingResult",
    "TopicIntent",
    "TribeClient",
    "TribeWindowInput",
    "Unit",
    "ViralityDiagnostic",
    "Window",
    "WindowAcousticFeatures",
    "WindowTopicMatch",
    "Word",
    "YamnetBackend",
    "YamnetEventResult",
    "YamnetOnnxDetector",
    "analyze_pcm_window",
    "analyze_wav_window",
    "build_units",
    "classify_commercial_intent",
    "commercial_score",
    "compute_texttiling",
    "cosine_similarity",
    "detect_intro_teasers",
    "discourse_coherence_bonus",
    "discourse_opening_advance",
    "embed_text",
    "embed_units",
    "enumerate_windows",
    "extract_pitch_track_yin",
    "extract_window_acoustic_features",
    "extract_yamnet_patches",
    "fetch_sponsorblock_segments_py",
    "filter_candidates_by_topic_semantics",
    "filter_commercial_windows",
    "filter_windows_by_duration",
    "highlights_job_key",
    "is_commercial_segment",
    "is_incomplete_closing",
    "load_yamnet_detector",
    "padded_windows",
    "parse_topic_intent",
    "prefilter_candidates_for_topic",
    "score_windows_for_topic",
    "snap_to_silence",
    "snap_to_silence_ms",
    "snap_window_to_silence",
    "snap_windows",
    "words_to_silence_gaps",
]
