"""Generate ``clip.wav`` — the 5-second speech-like fixture, from scratch.

Run it to reproduce the committed file byte for byte:

```bash
python worker_ai/fixtures/speech-5s/make_clip.py
```

## Why it is synthesised rather than recorded

Two tests need a real audio file rather than a tone: the `slow` LocalWhisper test,
which would otherwise assert nothing about a model it never fed, and the eval
harness's vendor lanes, which skip a set with no media. Recording a human is the
better fixture and belongs to **A00-05**, which is building the labelled Hinglish
set. Until then, committing someone else's clip means committing someone else's
licence, and shipping a sine tone means the model gets nothing to work on.

So this generates one: a five-second source-filter synthesis — a glottal pulse
train with a wandering pitch, shaped by three formants that move between vowel
targets, gated into syllables and interrupted by short stops. It is not speech and
no model will transcribe it into words. It **is** a signal with speech's spectral
envelope, syllable rate and energy contour, which is what makes it a real
exercise of a decode path, a VAD and a language-identification window rather than
a placeholder.

## Licence

Everything here is generated by this script from constants in this file, so the
output is an original work of this repository, dedicated to the public domain
under **CC0-1.0** (see ``LICENSE``). No third-party audio, no attribution
obligation, no clearance question.
"""

from __future__ import annotations

import math
import wave
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

SAMPLE_RATE = 16_000
DURATION_S = 5.0
#: Fixed so the file is byte-identical on every machine.
SEED = 20260902

#: (F1, F2, F3) in hertz, roughly the Hindi vowel space.
VOWELS: tuple[tuple[float, float, float], ...] = (
    (730, 1090, 2440),  # a
    (300, 2290, 3010),  # i
    (325, 700, 2530),  # u
    (530, 1840, 2480),  # e
    (570, 840, 2410),  # o
)

#: Syllables per second — normal conversational Hindi is about 5.
SYLLABLE_RATE = 5.0


def _glottal_pulses(samples: int, rng: np.random.Generator) -> NDArray[np.float32]:
    """A pulse train with a wandering fundamental: the voice source."""
    time = np.arange(samples, dtype=np.float64) / SAMPLE_RATE
    # 130 Hz with a slow drift and a little jitter, as a real voice has.
    f0 = 130.0 + 12.0 * np.sin(2 * math.pi * 0.35 * time) + rng.normal(0, 1.2, samples)
    phase = np.cumsum(2 * math.pi * f0 / SAMPLE_RATE)
    # A sawtooth is a decent glottal source: rich in harmonics, cheap to make.
    source = 2.0 * (phase / (2 * math.pi) % 1.0) - 1.0
    return source.astype(np.float32)


def _formant(signal: NDArray[np.float32], centre: float, bandwidth: float) -> NDArray[np.float32]:
    """One two-pole resonator, applied sample by sample."""
    radius = math.exp(-math.pi * bandwidth / SAMPLE_RATE)
    theta = 2 * math.pi * centre / SAMPLE_RATE
    a1 = -2.0 * radius * math.cos(theta)
    a2 = radius * radius
    gain = 1.0 - radius
    out = np.zeros_like(signal)
    previous = second_previous = 0.0
    for index, value in enumerate(signal):
        current = gain * float(value) - a1 * previous - a2 * second_previous
        out[index] = current
        second_previous, previous = previous, current
    return out


def _envelope(samples: int, rng: np.random.Generator) -> NDArray[np.float32]:
    """Syllable gating: energy rises and falls, with occasional stops."""
    time = np.arange(samples, dtype=np.float64) / SAMPLE_RATE
    syllables = 0.5 + 0.5 * np.sin(2 * math.pi * SYLLABLE_RATE * time - math.pi / 2)
    envelope = 0.25 + 0.75 * syllables
    # Three short stops, the way a phrase has closures.
    for start in (0.9, 2.3, 3.8):
        begin = int(start * SAMPLE_RATE)
        envelope[begin : begin + int(0.09 * SAMPLE_RATE)] *= 0.05
    # Two breaths of near-silence, so a VAD has something to find.
    for start, length in ((1.55, 0.30), (3.15, 0.35)):
        begin = int(start * SAMPLE_RATE)
        envelope[begin : begin + int(length * SAMPLE_RATE)] *= 0.02
    envelope *= 1.0 + rng.normal(0, 0.02, samples)
    return np.clip(envelope, 0.0, 1.5).astype(np.float32)


def synthesise() -> NDArray[np.float32]:
    """The clip, as float32 in [-1, 1]."""
    rng = np.random.default_rng(SEED)
    samples = int(SAMPLE_RATE * DURATION_S)
    source = _glottal_pulses(samples, rng)

    # Move through the vowel space one vowel per 400 ms, cross-faded.
    step = int(0.4 * SAMPLE_RATE)
    voiced = np.zeros(samples, dtype=np.float32)
    for index in range(0, samples, step):
        end = min(samples, index + step)
        f1, f2, f3 = VOWELS[(index // step) % len(VOWELS)]
        segment = source[index:end]
        shaped = (
            _formant(segment, f1, 80)
            + 0.6 * _formant(segment, f2, 110)
            + 0.3 * _formant(segment, f3, 160)
        )
        fade = np.hanning(len(shaped)).astype(np.float32) if len(shaped) > 2 else 1.0
        voiced[index:end] = shaped * fade

    # A whisper of fricative noise, so the spectrum is not purely harmonic.
    noise = rng.normal(0, 0.012, samples).astype(np.float32)
    clip = (voiced + noise) * _envelope(samples, rng)

    peak = float(np.max(np.abs(clip))) or 1.0
    return (clip / peak * 0.7).astype(np.float32)


def write(path: Path) -> Path:
    """Write 16-bit mono PCM at 16 kHz — the format the pipeline reads."""
    pcm = np.clip(synthesise(), -1.0, 1.0)
    with wave.open(str(path), "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(SAMPLE_RATE)
        handle.writeframes((pcm * 32767.0).astype("<i2").tobytes())
    return path


if __name__ == "__main__":
    written = write(Path(__file__).with_name("clip.wav"))
    print("wrote", written, written.stat().st_size, "bytes")
