import { describe, expect, it } from "vitest";

import {
  EPISODE_PACK_EXPECTED_POLL_MS,
  EPISODE_PACK_WRITING_POLL_MS,
  clipCopyOf,
  episodePackPollDelay,
  episodePackQueryKey,
  judgementOf,
} from "./repurpose-copy.js";

import type { RepurposeEpisodePackView } from "./repurpose-copy.js";

const COPY = {
  summary: "Salary badhne par bhi paise kyun nahi bachte.",
  hook: "Yeh galti sab karte hain",
  cta: "Poora video zaroor dekhiye.",
  hashtags: ["#money"],
  locale: "hi-Latn",
  title: "Salary se ameer kyun nahi bante?",
};

describe("clipCopyOf", () => {
  it("reads a whole copy", () => {
    expect(clipCopyOf(COPY)?.title).toBe("Salary se ameer kyun nahi bante?");
  });

  it("reads the column's `{}`, a null or a partial copy as none", () => {
    expect(clipCopyOf({})).toBeNull();
    expect(clipCopyOf(null)).toBeNull();
    expect(clipCopyOf(undefined)).toBeNull();
    expect(clipCopyOf({ ...COPY, hashtags: "#money" })).toBeNull();
    expect(clipCopyOf([COPY])).toBeNull();
  });
});

describe("judgementOf", () => {
  it("reads the model's scores, and nothing else", () => {
    const judgement = { standalone: 8, payoff: 7, humour: 2, model: "sarvam-105b-conversations" };
    expect(judgementOf(judgement)).toEqual(judgement);
    expect(judgementOf(null)).toBeNull();
    expect(judgementOf({ standalone: 8 })).toBeNull();
  });
});

describe("episodePackPollDelay", () => {
  const view = (status: RepurposeEpisodePackView["status"]): RepurposeEpisodePackView => ({
    runId: "01RUN",
    status,
    pack: null,
    createdAt: null,
    disclosure: "Generated by AI from your transcript",
  });

  it("polls while the text is being written", () => {
    expect(episodePackPollDelay(view("writing"), false)).toBe(EPISODE_PACK_WRITING_POLL_MS);
  });

  it("polls slowly while it is expected to start, and not at all otherwise", () => {
    expect(episodePackPollDelay(view("none"), true)).toBe(EPISODE_PACK_EXPECTED_POLL_MS);
    expect(episodePackPollDelay(undefined, true)).toBe(EPISODE_PACK_EXPECTED_POLL_MS);
    expect(episodePackPollDelay(view("none"), false)).toBe(false);
    expect(episodePackPollDelay(view("ready"), true)).toBe(false);
    expect(episodePackPollDelay(view("failed"), true)).toBe(false);
  });
});

it("keeps the pack under its run's key, so the run's invalidation refreshes it", () => {
  expect(episodePackQueryKey("WS", "RUN")).toEqual([
    "ws",
    "WS",
    "repurpose",
    "runs",
    "RUN",
    "episode-pack",
  ]);
});
