/**
 * Curated 50-Item Micro-SFX Library Registry (Pillar 5 §06).
 *
 * Implements Submagic-grade semantic contextual sound effects:
 * - 50 commercially cleared 24-bit 48kHz WAV assets across 5 primary categories
 * - Anti-fatigue throttle spacing: >= 2.5 seconds (2500 ms)
 * - Calibrated non-intrusive mixing level: -18 dBFS
 * - Frame-accurate alignment with visual events (camera zooms, emoji pops, kinetic typography)
 */

export type SfxCategory = "whoosh" | "pop" | "ding" | "cash" | "impact";

export interface SfxAsset {
  readonly id: string;
  readonly title: string;
  readonly category: SfxCategory;
  readonly cueType: "whoosh" | "pop" | "ding" | "notification" | "impact" | "boom" | "riser";
  readonly tags: readonly string[];
  readonly durationSec: number;
  readonly fileName: string;
  readonly calibratedGainDb: number;
  readonly defaultVolume: number;
}

/** Default calibrated non-intrusive audio level per SLA spec (-18 dBFS). */
export const SFX_CALIBRATED_GAIN_DB = -18.0;

/** Default Remotion preview volume slider (0.0 to 1.0) calibrated for micro-SFX. */
export const SFX_DEFAULT_REMOTION_VOLUME = 0.4;

/** Minimum spacing in ms between automatic SFX cues to prevent auditory fatigue (2.5s). */
export const SFX_MIN_PACING_THROTTLE_MS = 2500;

export const SFX_LIBRARY: readonly SfxAsset[] = [
  // WHOOSH (1-10)
  {
    id: "whoosh_fast",
    title: "Whoosh Fast",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "fast", "whip", "air"],
    durationSec: 0.35,
    fileName: "whoosh_fast.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_cinematic",
    title: "Whoosh Cinematic",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "cinematic", "deep", "transition"],
    durationSec: 0.65,
    fileName: "whoosh_cinematic.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_whip",
    title: "Whoosh Whip",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "whip", "snap", "fast"],
    durationSec: 0.28,
    fileName: "whoosh_whip.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_air",
    title: "Whoosh Air",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "air", "breath", "subtle"],
    durationSec: 0.45,
    fileName: "whoosh_air.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_swish",
    title: "Whoosh Swish",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "swish", "clean"],
    durationSec: 0.32,
    fileName: "whoosh_swish.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_transition",
    title: "Whoosh Transition",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "transition", "camera", "cut"],
    durationSec: 0.55,
    fileName: "whoosh_transition.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_sweep",
    title: "Whoosh Sweep",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "sweep", "pan"],
    durationSec: 0.48,
    fileName: "whoosh_sweep.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_soft",
    title: "Whoosh Soft",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "soft", "gentle"],
    durationSec: 0.4,
    fileName: "whoosh_soft.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_reverse",
    title: "Whoosh Reverse",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "reverse", "riser"],
    durationSec: 0.5,
    fileName: "whoosh_reverse.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "whoosh_snap",
    title: "Whoosh Snap",
    category: "whoosh",
    cueType: "whoosh",
    tags: ["whoosh", "snap", "quick"],
    durationSec: 0.25,
    fileName: "whoosh_snap.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },

  // POP (11-20)
  {
    id: "pop_bubble",
    title: "Pop Bubble",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "bubble", "wooden", "emoji"],
    durationSec: 0.18,
    fileName: "pop_bubble.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_wood",
    title: "Pop Wood",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "wood", "block", "click"],
    durationSec: 0.15,
    fileName: "pop_wood.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_soft",
    title: "Pop Soft",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "soft", "subtle"],
    durationSec: 0.16,
    fileName: "pop_soft.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_cork",
    title: "Pop Cork",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "cork", "plop"],
    durationSec: 0.22,
    fileName: "pop_cork.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_plop",
    title: "Pop Plop",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "plop", "water"],
    durationSec: 0.2,
    fileName: "pop_plop.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_mouth",
    title: "Pop Mouth",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "mouth", "organic"],
    durationSec: 0.14,
    fileName: "pop_mouth.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_click",
    title: "Pop Click",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "click", "ui"],
    durationSec: 0.12,
    fileName: "pop_click.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_snap",
    title: "Pop Snap",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "snap", "finger"],
    durationSec: 0.15,
    fileName: "pop_snap.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_blip",
    title: "Pop Blip",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "blip", "digital"],
    durationSec: 0.13,
    fileName: "pop_blip.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "pop_cartoon",
    title: "Pop Cartoon",
    category: "pop",
    cueType: "pop",
    tags: ["pop", "cartoon", "fun"],
    durationSec: 0.25,
    fileName: "pop_cartoon.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },

  // DING / CHIME (21-30)
  {
    id: "ding_bell",
    title: "Ding Bell",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "bell", "chime", "success"],
    durationSec: 0.85,
    fileName: "ding_bell.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_success",
    title: "Ding Success",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "success", "achievement"],
    durationSec: 0.95,
    fileName: "ding_success.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_notification",
    title: "Ding Notification",
    category: "ding",
    cueType: "notification",
    tags: ["ding", "notification", "ping", "ui"],
    durationSec: 0.6,
    fileName: "ding_notification.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_sparkle",
    title: "Ding Sparkle",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "sparkle", "magic"],
    durationSec: 1.1,
    fileName: "ding_sparkle.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_crystal",
    title: "Ding Crystal",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "crystal", "glass"],
    durationSec: 0.9,
    fileName: "ding_crystal.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_elevator",
    title: "Ding Elevator",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "elevator", "service"],
    durationSec: 1.2,
    fileName: "ding_elevator.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_service",
    title: "Ding Service Bell",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "service", "desk"],
    durationSec: 0.75,
    fileName: "ding_service.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_soft",
    title: "Ding Soft",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "soft", "accent"],
    durationSec: 0.7,
    fileName: "ding_soft.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_chime_high",
    title: "Ding Chime High",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "chime", "high"],
    durationSec: 0.8,
    fileName: "ding_chime_high.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "ding_chime_subtle",
    title: "Ding Chime Subtle",
    category: "ding",
    cueType: "ding",
    tags: ["ding", "chime", "subtle"],
    durationSec: 0.65,
    fileName: "ding_chime_subtle.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },

  // CASH / MONEY (31-40)
  {
    id: "cash_register",
    title: "Cash Register",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "money", "register", "ka-ching"],
    durationSec: 0.95,
    fileName: "cash_register.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_ka_ching",
    title: "Cash Ka-Ching",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "ka-ching", "dollar", "wealth"],
    durationSec: 1.05,
    fileName: "cash_ka_ching.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_coin_clink",
    title: "Cash Coin Clink",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "coin", "clink", "crypto"],
    durationSec: 0.7,
    fileName: "cash_coin_clink.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_coin_drop",
    title: "Cash Coin Drop",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "coin", "drop", "payment"],
    durationSec: 0.8,
    fileName: "cash_coin_drop.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_register_drawer",
    title: "Cash Register Drawer",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "drawer", "retail"],
    durationSec: 0.9,
    fileName: "cash_register_drawer.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_jackpot",
    title: "Cash Jackpot",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "jackpot", "win", "coins"],
    durationSec: 1.25,
    fileName: "cash_jackpot.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_coins_shake",
    title: "Cash Coins Shake",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "coins", "shake"],
    durationSec: 0.75,
    fileName: "cash_coins_shake.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_pay_ding",
    title: "Cash Pay Ding",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "pay", "digital"],
    durationSec: 0.65,
    fileName: "cash_pay_ding.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_digital_beep",
    title: "Cash Digital Beep",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "digital", "pos", "terminal"],
    durationSec: 0.5,
    fileName: "cash_digital_beep.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "cash_money_counter",
    title: "Cash Money Counter",
    category: "cash",
    cueType: "ding",
    tags: ["cash", "counter", "bills"],
    durationSec: 0.85,
    fileName: "cash_money_counter.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },

  // IMPACT / BOOM / CINEMATIC (41-50)
  {
    id: "cinematic_hit",
    title: "Cinematic Hit",
    category: "impact",
    cueType: "impact",
    tags: ["impact", "cinematic", "sub", "hit", "hook"],
    durationSec: 1.4,
    fileName: "cinematic_hit.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_bass_thud",
    title: "Impact Bass Thud",
    category: "impact",
    cueType: "impact",
    tags: ["impact", "bass", "thud", "sub"],
    durationSec: 1.1,
    fileName: "impact_bass_thud.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_sub_boom",
    title: "Impact Sub Boom",
    category: "impact",
    cueType: "boom",
    tags: ["boom", "sub", "deep", "drop"],
    durationSec: 1.6,
    fileName: "impact_sub_boom.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_riser",
    title: "Impact Riser",
    category: "impact",
    cueType: "riser",
    tags: ["riser", "impact", "climax"],
    durationSec: 1.2,
    fileName: "impact_riser.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_punch",
    title: "Impact Punch",
    category: "impact",
    cueType: "impact",
    tags: ["impact", "punch", "strike"],
    durationSec: 0.9,
    fileName: "impact_punch.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_stomp",
    title: "Impact Stomp",
    category: "impact",
    cueType: "impact",
    tags: ["impact", "stomp", "heavy"],
    durationSec: 1.05,
    fileName: "impact_stomp.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_slam",
    title: "Impact Slam",
    category: "impact",
    cueType: "impact",
    tags: ["impact", "slam", "dramatic"],
    durationSec: 1.15,
    fileName: "impact_slam.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_deep_drop",
    title: "Impact Deep Drop",
    category: "impact",
    cueType: "boom",
    tags: ["boom", "drop", "cinematic"],
    durationSec: 1.5,
    fileName: "impact_deep_drop.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_dark_drone",
    title: "Impact Dark Drone",
    category: "impact",
    cueType: "impact",
    tags: ["impact", "dark", "sub"],
    durationSec: 1.35,
    fileName: "impact_dark_drone.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
  {
    id: "impact_sub_drop",
    title: "Impact Sub Drop",
    category: "impact",
    cueType: "boom",
    tags: ["boom", "sub", "drop", "808"],
    durationSec: 1.45,
    fileName: "impact_sub_drop.wav",
    calibratedGainDb: SFX_CALIBRATED_GAIN_DB,
    defaultVolume: SFX_DEFAULT_REMOTION_VOLUME,
  },
] as const;

export const SFX_BY_ID: Readonly<Record<string, SfxAsset>> = Object.freeze(
  Object.fromEntries(SFX_LIBRARY.map((asset) => [asset.id, asset])),
);

export const SFX_BY_CATEGORY: Readonly<Record<SfxCategory, readonly SfxAsset[]>> = Object.freeze({
  whoosh: SFX_LIBRARY.filter((a) => a.category === "whoosh"),
  pop: SFX_LIBRARY.filter((a) => a.category === "pop"),
  ding: SFX_LIBRARY.filter((a) => a.category === "ding"),
  cash: SFX_LIBRARY.filter((a) => a.category === "cash"),
  impact: SFX_LIBRARY.filter((a) => a.category === "impact"),
});

export function getSfxAsset(id: string): SfxAsset | undefined {
  return SFX_BY_ID[id];
}

export function matchSfxForTrigger(
  trigger: "zoom" | "emoji" | "money" | "hook" | "emphasis" | "question",
): SfxAsset {
  switch (trigger) {
    case "zoom":
      return SFX_BY_ID["whoosh_fast"] ?? SFX_LIBRARY[0]!;
    case "emoji":
      return SFX_BY_ID["pop_bubble"] ?? SFX_LIBRARY[10]!;
    case "money":
      return SFX_BY_ID["cash_ka_ching"] ?? SFX_BY_ID["cash_register"] ?? SFX_LIBRARY[30]!;
    case "hook":
      return SFX_BY_ID["cinematic_hit"] ?? SFX_LIBRARY[40]!;
    case "emphasis":
      return SFX_BY_ID["ding_bell"] ?? SFX_LIBRARY[20]!;
    case "question":
      return SFX_BY_ID["ding_notification"] ?? SFX_LIBRARY[22]!;
  }
}
