import swc from "unplugin-swc";
import { defineConfig, mergeConfig } from "vitest/config";

import { coverageThresholds, vitestBaseConfig } from "@montaj/config/vitest";

export default mergeConfig(
  defineConfig(vitestBaseConfig),
  defineConfig({
    // NestJS DI reads `design:paramtypes`, which esbuild cannot emit; SWC can.
    plugins: [swc.vite({ module: { type: "es6" } })],
    test: {
      name: "@montaj/api",
      root: "./",
      include: ["src/**/*.test.ts", "prisma/**/*.test.ts", "test/**/*.e2e-spec.ts"],
      setupFiles: ["./test/setup-env.ts"],
      // The integration suite starts a testcontainers Postgres at collection time.
      testTimeout: 30_000,
      hookTimeout: 180_000,
    },
  }),
  // CONTRACTS §9: apps/api is 75/70 (lines/branches).
  defineConfig(coverageThresholds({ lines: 75, branches: 70 })),
  defineConfig({
    test: {
      coverage: {
        exclude: [
          "**/dist/**",
          "**/*.test.ts",
          "**/*.config.*",
          "**/index.ts",
          // Generated by `prisma generate`; CONTRACTS §9 excludes generated code.
          "**/generated/**",
          "prisma/migrations/**",
          // Process entry points: exercised by `pnpm dev` and CI, not by unit tests.
          "src/main.ts",
          "scripts/**",
        ],
      },
    },
  }),
);
