import swc from "unplugin-swc";
import { defineConfig, mergeConfig } from "vitest/config";

import { coverageThresholds, vitestBaseConfig } from "@montaj/config/vitest";

/**
 * `mergeConfig(a, b, isRootConfig?)` takes TWO configs and a boolean, so the
 * merges are chained rather than passed as a list: a four-argument call silently
 * treats the third config as `isRootConfig` and drops the fourth, which is how
 * the CONTRACTS section 9 coverage gate and the exclude list both stopped being
 * applied (found while landing A04).
 */
const withSettings = mergeConfig(
  defineConfig(vitestBaseConfig),
  defineConfig({
    // NestJS DI reads `design:paramtypes`, which esbuild cannot emit; SWC can.
    plugins: [swc.vite({ module: { type: "es6" } })],
    test: {
      name: "@montaj/api",
      root: "./",
      include: ["src/**/*.test.ts", "prisma/**/*.test.ts", "test/**/*.e2e-spec.ts"],
      setupFiles: ["./test/setup-env.ts"],
      // A23a: one PostgreSQL and one Redis for the WHOLE run (or the servers
      // `TEST_DATABASE_URL` / `TEST_REDIS_URL` point at), plus a template database
      // migrated once. Each suite then clones the template and takes a logical
      // Redis database of its own, so file parallelism stays on and Docker is
      // asked for two containers instead of one per suite.
      globalSetup: ["./test/global-setup.ts"],
      testTimeout: 30_000,
      // Generous, but no longer because a hook might be pulling an image: a suite
      // hook now clones a database (a file copy) and boots Nest.
      hookTimeout: 180_000,
      // The run teardown drops whatever a suite's `afterAll` could not: one
      // `DROP DATABASE` per suite, sequentially, each forcing a checkpoint. The
      // 10s default is a fraction of what that needs on a busy machine.
      teardownTimeout: 180_000,
    },
  }),
);

const withCoverageScope = mergeConfig(
  withSettings,
  defineConfig({
    test: {
      coverage: {
        exclude: [
          "**/dist/**",
          "**/*.test.ts",
          "**/*.config.*",
          "**/index.ts",
          // Generated by `prisma generate`; CONTRACTS section 9 excludes generated code.
          "**/generated/**",
          // `pnpm gen:client` compiles the app here before running the generator:
          // build output, and a duplicate of `src/` that would halve every ratio.
          "**/.openapi/**",
          "prisma/migrations/**",
          // Seed and migration data: exercised by `db:seed`, asserted by its own
          // test, and mostly literal tables.
          "prisma/seed*.ts",
          // Process entry points: exercised by `pnpm dev` and CI, not by unit tests.
          "src/main.ts",
          "scripts/**",
          "test/**",
        ],
      },
    },
  }),
);

// CONTRACTS section 9: apps/api is 75/70 (lines/branches).
export default mergeConfig(
  withCoverageScope,
  defineConfig(coverageThresholds({ lines: 75, branches: 70 })),
);
