import swc from "unplugin-swc";
import { defineConfig, mergeConfig } from "vitest/config";

import { coverageThresholds, vitestBaseConfig } from "@montaj/config/vitest";

/**
 * `mergeConfig(a, b, isRootConfig?)` takes TWO configs and a boolean, so the
 * merges are chained rather than passed as a list: a four-argument call silently
 * treats the third config as `isRootConfig` and drops the fourth, which is how
 * the CONTRACTS section 9 coverage gate and the exclude list both stopped being
 * applied (found while landing A04).
 */
const withSettings = mergeConfig(
  defineConfig(vitestBaseConfig),
  defineConfig({
    // NestJS DI reads `design:paramtypes`, which esbuild cannot emit; SWC can.
    plugins: [swc.vite({ module: { type: "es6" } })],
    test: {
      name: "@montaj/api",
      root: "./",
      include: ["src/**/*.test.ts", "prisma/**/*.test.ts", "test/**/*.e2e-spec.ts"],
      setupFiles: ["./test/setup-env.ts"],
      // The integration suites start testcontainers at collection time.
      testTimeout: 30_000,
      hookTimeout: 180_000,
    },
  }),
);

const withCoverageScope = mergeConfig(
  withSettings,
  defineConfig({
    test: {
      coverage: {
        exclude: [
          "**/dist/**",
          "**/*.test.ts",
          "**/*.config.*",
          "**/index.ts",
          // Generated by `prisma generate`; CONTRACTS section 9 excludes generated code.
          "**/generated/**",
          // `pnpm gen:client` compiles the app here before running the generator:
          // build output, and a duplicate of `src/` that would halve every ratio.
          "**/.openapi/**",
          "prisma/migrations/**",
          // Seed and migration data: exercised by `db:seed`, asserted by its own
          // test, and mostly literal tables.
          "prisma/seed*.ts",
          // Process entry points: exercised by `pnpm dev` and CI, not by unit tests.
          "src/main.ts",
          "scripts/**",
          "test/**",
        ],
      },
    },
  }),
);

// CONTRACTS section 9: apps/api is 75/70 (lines/branches).
export default mergeConfig(
  withCoverageScope,
  defineConfig(coverageThresholds({ lines: 75, branches: 70 })),
);
